version: 0.2


phases:
   install:
     runtime-versions:
       docker: 18
       java: corretto11
   pre_build:
     commands:
     - echo Logging in to Amazon ECR...
     - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 156962844638.dkr.ecr.us-west-2.amazonaws.com
   build:
     commands:
     - echo Build started on `date`
     - echo Building java
     - mvn clean package
     - echo Building the docker image
     - docker build -t authservice .
     - docker tag authservice:latest 156962844638.dkr.ecr.us-west-2.amazonaws.com/authservice:latest
   post_build:
     commands:
     - echo Build completed on `date`
     - docker push 156962844638.dkr.ecr.us-west-2.amazonaws.com/authservice:latest
     - echo Writing definition files
     - printf '[{"name":"authservice:latest","imageUri":"%s"}]' 156962844638.dkr.ecr.us-west-2.amazonaws.com/authservice:latest > imagedefinitions.json
artifacts:
  files:
  - imagedefinitions.json